### ISSUE TITLE
login problem

### ISSUE THREAD

**Issue by terrysahaidak** [v12/node-vk-api#5] opened 2015-12-16 17:58 UTC
Just tried to login with this code:

``` js
import {vkDirty} from '../utils/native'

export function login(name, pass) {
  const credentials = {
    client_id: 5120154,
    login:        name,
    pass:         pass,
    tokenStorage: new vkDirty.TokenStorage()
  }
  vkDirty.token(credentials)
  .then(token => console.log(token))
  .catch(err => console.log('Unnable to auth: ' + err))
}
```

And got this error

```
Unnable to auth: ValidationError: Invalid parameter {
  "client_id" [31m[1][0m: null
}
[31m
[1] "client_id" must be a number[0m
```

**Comment by v12** [comment] 2015-12-16 23:09
Unfortunately, I wasn't able to reproduce the error. Credentials object validation is done using [Joi](https://github.com/hapijs/joi). Client ID is check for being [positive integer](https://github.com/hapijs/joi/blob/master/API.md#number), which will work fine even if the parameter is string but can be converted to number.

I'm afraid but I can't even think about anything that might help you to find out the reason of this issue. I'd suggest to go through the stack and find the code where check fails. :beetle: 

Let me know if you manage to find out why it happens. I'm closing the issue for now but feel free to reopen it if you have any further details. Thank you!

**Closed as completed by v12** 2015-12-16 23:09 UTC
Labels: unconfirmed

**Comment by terrysahaidak** [comment] 2015-12-17 14:46
It was because I'm using it within the remote call in the electron (a.k.a. atom-shell), but after switching to ipcMain/ipcRender almost everything is working, but still getting an error "phone is required" even my login is not a phone number, but after removing several lines of your code it works great.

``` js
// i've removed it from paramsSchema code
.when('login', {
  is:        joi.string().regex(phoneRegexp),
  otherwise: joi.required()
}),
```
